version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - /var/log/nginx:/var/log/nginx
    networks:
      - nginx_proxy

  nginx_gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx_gen
    restart: always
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - nginx_proxy

  duic:
    image: zhudyos/duic
    environment:
      - VIRTUAL_HOST=duic.zhudy.io
      - VIRTUAL_NETWORK=nginx_proxy
      - VIRTUAL_PORT=7777
    volumes:
      - ./config:/app/config
    networks:
      - nginx_proxy
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data:

networks:
  nginx_proxy:
    external:
      name: nginx_proxy
  backend:
