version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
#    restart: always
    volumes:
      - nginx_conf:/etc/nginx/conf.d:ro
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - nginx_proxy
      - frontend

  nginx_gen:
    image: jwilder/docker-gen
    container_name: jwilder_gen
#    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d:rw
      - nginx_vhost:/etc/nginx/vhost.d:rw
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - nginx_proxy

  nginx_letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: jrcs_letsencrypt
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx
#    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
    networks:
      - nginx_proxy

  duic:
    image: zhudyos/duic
    environment:
      - VIRTUAL_HOST=duic.zhudy.io
      - VIRTUAL_NETWORK=nginx_proxy
      - VIRTUAL_PORT=7777
      - LETSENCRYPT_HOST=dui.zhudy.io
      - LETSENCRYPT_EMAIL=kevinz@weghst.com
    volumes:
      - ./config:/config
    networks:
      - frontend
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  nginx_conf:
    external:
      name: nginx_conf
  nginx_vhost:
    external:
      name: nginx_vhost
  nginx_html:
    external:
      name: nginx_html
  nginx_certs:
    external:
      name: nginx_certs
  mongo_data:
    external:
      name: mongo_data

networks:
  nginx_proxy:
  frontend:
  backend:
